// Generated by CoffeeScript 1.10.0
(function() {
  var Node;

  Node = {
    onMessage: function(msg) {
      return console.log(msg.message);
    }
  };

  self.onmessage = function(msg) {
    var e, error, func;
    try {
      func = "on" + msg.data.type;
      return Node[func](msg.data);
    } catch (error) {
      e = error;
      return console.log(e);
    }
  };

}).call(this);
