// Generated by CoffeeScript 1.10.0
(function() {
  var Run, inPorts, outPorts;

  inPorts = {
    "IN": {
      ips: []
    },
    "MULT": {
      ips: []
    }
  };

  outPorts = {
    "OUT": {
      ips: []
    }
  };

  self.onmessage = function(msg) {
    var count, doit, e, error, name, numberPorts, port, ports, results;
    try {
      inPorts[msg.data.port].ips.push(msg.data.ip);
      numberPorts = 0;
      doit = (function() {
        var results;
        results = [];
        for (name in inPorts) {
          port = inPorts[name];
          numberPorts += 1;
          if (port.ips.length > 0) {
            results.push(1);
          } else {
            results.push(0);
          }
        }
        return results;
      })();
      count = inPorts.reduce(function(t, s) {
        return t.ips.length + s.ips.length;
      });
      if (count === numberPorts) {
        ports = {};
        for (name in inPorts) {
          port = inPorts[name];
          ports[name] = port.ips.pop;
        }
        for (name in outPorts) {
          port = outPorts[name];
          ports[name] = [];
        }
      }
      results = [];
      for (name in outPorts) {
        port = outPorts[name];
        if (port.ips.length > 0) {
          results.push(self.postMessage({
            port: name,
            ip: port.ips.pop
          }));
        } else {
          results.push(void 0);
        }
      }
      return results;
    } catch (error) {
      e = error;
      return console.log(e);
    }
  };

  Run = function(ports) {
    var i, m;
    i = ports["IN"];
    m = ports["MULT"];
    return ports["OUT"].ips.push(m * i);
  };

}).call(this);
