// Generated by CoffeeScript 1.10.0
(function() {
  var emitter, net;

  Class(Network({
    nodes: [],
    constructor: function() {},
    defProc: function(file) {
      var worker;
      worker = new Worker("js/node.js");
      return worker.postMessage({
        cmd: "load",
        file: file
      });
    }
  }));

  net = new Network;

  emitter = net.defProc("js/emitter.js");


  /*
  get.postMessage
    port: "IN"
    ip: "4"
  
  get.postMessage
    port: "MULT"
    ip: "13"
   */

}).call(this);
