// Generated by CoffeeScript 1.10.0
(function() {
  var Queue;

  Queue = (function() {
    Queue.prototype.ips = [];

    function Queue(i, o, len) {
      this.i = i;
      this.o = o;
      this.len = len;
      if (this.len == null) {
        this.len = 10;
      }
      this.i.onmessage = function(msg) {
        var result;
        result = "queued";
        if (this.ips.length >= this.len) {
          result = "rejected";
        } else {
          this.ips.push(msg.data);
        }
        return this.i.postMessage(result);
      };
      this.o.onmessage = function(msg) {
        if (this.ips.length <= 0) {
          return this.o.postMessage({
            empty: true
          });
        } else {
          return this.o.postMessage(this.len.pop());
        }
      };
    }

    return Queue;

  })();

}).call(this);
